/** @type {import('tailwindcss').Config} */
export default {
    content: [
        "./index.html",
        "./src/**/*.{vue,js,ts,jsx,tsx}"
    ],
    theme: {
        extend: {
            colors: {
                "surface-container-low": "#fff0ef",
                "error-container": "#ffdad6",
                "secondary": "#715858",
                "on-secondary-fixed-variant": "#584141",
                "on-error": "#ffffff",
                "success": "#059669",
                "warning": "#D97706",
                "on-primary-fixed": "#410003",
                "engagement-biz": "#D97706",
                "outline": "#8c716e",
                "on-primary-fixed-variant": "#8a1a1a",
                "on-secondary-fixed": "#291717",
                "secondary-fixed-dim": "#dfbfbe",
                "tertiary-fixed": "#cae6ff",
                "engagement-lab": "#0D9488",
                "on-primary-container": "#ff9a91",
                "on-secondary": "#ffffff",
                "primary": "#8B1A1A",
                "canvas": "#F7F7F7",
                "background": "#fff8f7",
                "role-bm": "#7C3AED",
                "surface-dim": "#ecd5d2",
                "surface-variant": "#f5dddb",
                "surface-container-high": "#fbe3e0",
                "primary-ember": "#A82020",
                "tertiary": "#003450",
                "info": "#2563EB",
                "tertiary-fixed-dim": "#96ccf8",
                "info-mist": "#EFF6FF",
                "primary-deep": "#6B1212",
                "on-tertiary-fixed-variant": "#004b70",
                "role-ta": "#0369A1",
                "shell": "#1A0A0A",
                "shell-border": "#2D1515",
                "text-primary": "#1A1A2E",
                "text-secondary": "#6B7280",
                "text-disabled": "#9CA3AF",
                "text-inverse": "#FFFFFF",
                "neutral-50": "#FAFAFA",
                "neutral-100": "#F5F5F5",
                "neutral-200": "#E5E7EB",
                "neutral-300": "#D1D5DB",
                "on-tertiary-container": "#86bce7",
                "on-secondary-container": "#765c5c",
                "tertiary-container": "#004c71",
                "danger-mist": "#FEF2F2",
                "on-surface-variant": "#58413f",
                "success-mist": "#ECFDF5",
                "on-tertiary-fixed": "#001e30",
                "inverse-on-surface": "#ffedeb",
                "on-error-container": "#93000a",
                "outline-variant": "#e0bfbc",
                "on-background": "#251817",
                "primary-fixed": "#ffdad6",
                "surface-sunken": "#F0F0F0",
                "surface": "#FFFFFF",
                "role-instructor": "#0D9488",
                "surface-container": "#ffe9e6",
                "engagement-lecture": "#8B1A1A",
                "surface-container-lowest": "#ffffff",
                "error": "#ba1a1a",
                "surface-tint": "#ac322e",
                "primary-mist": "#F9EAEA",
                "surface-container-highest": "#f5dddb",
                "on-surface": "#251817",
                "warning-mist": "#FFFBEB",
                "surface-bright": "#fff8f7",
                "primary-container": "#8b1a1a",
                "secondary-fixed": "#fcdbd9",
                "danger": "#DC2626",
                "on-tertiary": "#ffffff",
                "secondary-container": "#fad8d7",
                "inverse-surface": "#3b2d2c",
                "primary-fixed-dim": "#ffb3ac",
                "on-primary": "#ffffff",
                "role-student": "#6B7280",
                "inverse-primary": "#ffb3ac",
            },
            borderRadius: {
                DEFAULT: "0.25rem",
                lg: "0.5rem",
                xl: "0.75rem",
                full: "9999px",
            },
            spacing: {
                "margin-desktop": "32px",
                "margin-mobile": "16px",
                "gutter": "24px",
                "base": "4px",
            },
            fontFamily: {
                "label-caps": ["DM Sans", "system-ui", "sans-serif"],
                "h1-mobile": ["DM Serif Display", "Georgia", "serif"],
                "display": ["DM Serif Display", "Georgia", "serif"],
                "h1": ["DM Serif Display", "Georgia", "serif"],
                "body-sm": ["DM Sans", "system-ui", "sans-serif"],
                "body-lg": ["DM Sans", "system-ui", "sans-serif"],
                "body-md": ["DM Sans", "system-ui", "sans-serif"],
                "label": ["DM Sans", "system-ui", "sans-serif"],
                "h2": ["DM Serif Display", "Georgia", "serif"],
                "kpi": ["DM Serif Display", "Georgia", "serif"],
                "mono": ["JetBrains Mono", "Courier New", "monospace"],
                "h3": ["DM Sans", "system-ui", "sans-serif"],
            },
            fontSize: {
                "label-caps": ["11px", { lineHeight: "1", letterSpacing: "0.08em", fontWeight: "600" }],
                "h1-mobile": ["28px", { lineHeight: "1.2", fontWeight: "400" }],
                "display": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "400" }],
                "h1": ["36px", { lineHeight: "1.15", letterSpacing: "-0.015em", fontWeight: "400" }],
                "body-sm": ["12px", { lineHeight: "1.4", fontWeight: "400" }],
                "body-lg": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
                "body-md": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
                "label": ["13px", { lineHeight: "1", letterSpacing: "0.01em", fontWeight: "500" }],
                "h2": ["28px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "400" }],
                "kpi": ["40px", { lineHeight: "1", fontWeight: "400" }],
                "mono": ["13px", { lineHeight: "1.5", fontWeight: "400" }],
                "h3": ["20px", { lineHeight: "1.3", fontWeight: "600" }],
            },
            boxShadow: {
                'elevated': '0 10px 15px -3px rgba(0, 0, 0, 0.08), 0 4px 6px -2px rgba(0, 0, 0, 0.04)',
            },
        },
    },
    plugins: [require('@tailwindcss/forms')],
}
